@startuml php
node "Web Browser" {
  node "Next.js" {
    [HTML]
    [JavaScript]
  }
  [pib]
  node "WebAssembly" {
    [PHP]
  }
}
[JavaScript] --> [pib] : 呼び出し
[pib] --> [PHP]
[PHP(src)] ..> emscripten : コンパイル
emscripten ..> [PHP]
@enduml

@startuml plantuml
node "GitHub Pages"{
  node "Next.js" {
      [JavaScript]
      [<img>]
  }
}
node "www.plantuml.com" {
  [plantuml/img]
}

[JavaScript] --> [<img>] : src URL構築
[<img>] --> [plantuml/img] : 画像リクエスト
@enduml

@startuml mermaid
node "GitHub pages" {
  node "Next.js" {
    [JavaScript]
    [<div>]
  }
  [mermaid.js]
}
[JavaScript] --down--> [mermaid.js] : 呼び出し
[mermaid.js] --> [<div>] : svg描画


@enduml

@startuml drawer
node "Web Browser" {
  node "Nextjs" {
    [JavaScript]
    [Canvas]
  }
  node "Tensorflow.js" {
    [モデル(js)]
  }
  [Tesseract.js]
}
[JavaScript] --> [Canvas]
[JavaScript] --> [モデル(js)]: 物体検出
[JavaScript] --> [Tesseract.js]: OCR

[手書き画像] ..> tensorflow: トレーニング
[ラベル情報] ..> tensorflow
tensorflow ..> [モデル]
[モデル] ..> tensorflowjs_wizard: ブラウザ向けに変換
tensorflowjs_wizard ..> [モデル(js)]

@enduml